M48
; DRILL file {KiCad 8.0.0} date 2024-03-07T02:07:13+0900
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-03-07T02:07:13+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1299
%
G90
G05
T1
X2.6772Y-3.9567
X2.7362Y-6.063
X5.748Y-4.3307
T2
X3.3622Y-6.0482
X3.8622Y-6.0482
M30
